### ISSUE TITLE
React-Native v0.59 FillType null object error with lottie-react-native v2.6.1

### ISSUE THREAD

**Issue by vladi-strilets** [lottie-react-native/lottie-react-native#498]
After upgrading React-Native to v0.59 because of some issues with Native Maps, I had to upgrade Gradle v3.3.0 and lottie-react-native v2.6.x. I was using v2.3.2 before and it worked perfectly, with v2.6.0 it shows the same animation doing .map() but I checked it with console and the json sources are different. And with v2.6.1 I'm getting the next crash error on open the screen that contains the lottie animation. 
 
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Path$FillType.nativeInt' on a null object reference
       at android.graphics.Path.setFillType(Path.java:268)
       at com.airbnb.lottie.animation.content.GradientFillContent.<init>(GradientFillContent.java:64)
       at com.airbnb.lottie.model.content.GradientFill.toContent(GradientFill.java:80)
       at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
       at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
       at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
       at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
       at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
       at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
       at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:47)
       at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
       at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:50)
       at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
       at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:236)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:198)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:482)
       at com.airbnb.lottie.LottieAnimationView$1.onCompositionLoaded(LottieAnimationView.java:81)
       at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
       at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

My Android build.gradle: 

```
android {
    compileSdkVersion 27
    buildToolsVersion "28.0.3"

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    ...
}
dependencies {
    implementation project(':lottie-react-native')
    implementation "com.android.support:appcompat-v7:28.0.0"
    implementation 'com.airbnb.android:lottie:2.5.6'
    ...
}
...
```
App build.gradle:
```
buildscript {
    ext {        
        supportLibVersion = "28.0.0"
        ...
    }
    repositories {
        jcenter()
        google()
        ...
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:4.0.0'
        ...
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()

    }
}
```
package.json
```
"react": "16.6.3",
"react-native": "^0.59.8",
"lottie-react-native": "2.6.1",
```

It looks like [this issue](https://github.com/airbnb/lottie-android/issues/925) with lottie-android. 

I'm testing the app on Samsung s9 with v9 of Android OS (Android 9 Pie). With v8 on simulator seems it works, so it had to be a problem with the Pie version of Android. 

Any idea? Thanks!

**Comment by vladistrilets** [comment]
Ok, the error was related with a gradient element. I had to remove it to getting code works. The element code is shown below, maybe someone could find the reason:
```
assets . layers . shapes: [{
	     "ty": "gf",
	     "o": {
		     "a": 0,
		     "k": 100
	     },
	     "g": {
		     "p": 3,
		     "k": {
			     "a": 0,
			     "k": [0, 0.976, 0.784, 0.4, 0.5, 0.976, 0.784, 0.4, 0.999, 0.976, 0.784, 0.4, 0, 1, 0.5, 0.5, 1, 0]
		     }
	     },
	     "s": {
		     "a": 0,
		     "k": [0, 0]
	     },
	     "e": {
		     "a": 0,
		     "k": [112.338, 3.156]
	     },
	     "t": 1,
	     "nm": "Gradient Fill 1",
	     "mn": "ADBE Vector Graphic - G-Fill"
             }, ... ]
```

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.
