### ISSUE TITLE
Unable to create layer for LottieAnimationView (HUAWEI)

### ISSUE THREAD

**Issue by HyeonjuPark** [lottie-react-native/lottie-react-native#632]
### Description

Crashing app with 'Unable to create layer for LottieAnimationView' Error

### Steps to Reproduce

1. On HUAWEI device honor 6x
2. Android version is 7

**Expected behavior:** 

**Actual behavior:** 

### Versions

My current lottie-react-native version is "3.3.2"
I think it's only happen on some specific devices. 
Similar issue is opened in lottie-android github here. But I couldn't figure out to solve.
https://github.com/airbnb/lottie-android/issues/1387

Error log is like this

```
Fatal Exception: java.lang.IllegalStateException: Unable to create layer for LottieAnimationView, see logcat for more info
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:356)
       at android.os.Looper.loop(Looper.java:138)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

Anyone has fixed this problem?

**Comment by asimonigh** [comment]
Same issue for me

**Comment by changety** [comment]
Same issue for me

**Comment by Wesely** [comment]
Same issue, we've got 57 crashes affecting 38 users in the past 7 days,
55% samsung, 16% Sony.
75% Android 5, 25% Android 9
