### ISSUE TITLE
Getting "IllegalArgumentException: Unknown color" exception

### ISSUE THREAD

**Issue by sagarshakya** [lottie-react-native/lottie-react-native#667]
### Description

We are seeing "IllegalArgumentException: Unknown color" exceptions on our app. 

### Steps to Reproduce

1. Unknown

### Error Message

```
java.lang.IllegalArgumentException: Unknown color
    at android.graphics.Color.parseColor(Color.java:1391)
    at com.airbnb.android.react.lottie.LottieAnimationViewPropertyManager.commitChanges(LottieAnimationViewPropertyManager.java:147)
    at com.airbnb.android.react.lottie.LottieAnimationViewManager.onAfterUpdateTransaction(LottieAnimationViewManager.java:224)
    at com.airbnb.android.react.lottie.LottieAnimationViewManager.onAfterUpdateTransaction(LottieAnimationViewManager.java:27)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:51)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:279)
    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:987)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:958)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:693)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

### Versions
`"lottie-ios": "^3.1.6",`
`"lottie-react-native": "^3.3.2",`
`"react": "16.11.0",`
`"react-native": "0.62.2"`

**Comment by crearo** [comment]
+1, I'm seeing the same. How does one debug something like this?

**Comment by ranjit-gfm** [comment]
+1
