### ISSUE TITLE
[Android] App crashes if lottie animation requires a font not found in the system

### ISSUE THREAD

**Issue by alfonsocj** [lottie-react-native/lottie-react-native#961]
### Description
The app crashes if there's a lottie animation that requires a font not found in the system and the prop `textFiltersAndroid` is available.

### Steps to Reproduce
- Implement a new `<AnimatedLottieView>` with an animation that uses a font not found in the system like https://lottiefiles.com/98337-3d-loop-button-with-text-change-option
- Add a text filter for Android `textFiltersAndroid={[{ keypath: 'Text - 1', text: 'TEST' }]}`
```
<AnimatedLottieView
      source={require('./animations/DynamicText.json')}
      autoPlay
      loop
      textFiltersAndroid={
        [
          {
            keypath: 'Text - 1',
            text: 'ANDROID',
          },
        ]
      }
/>
```

- Run on Android

**Expected behavior:** [What you expected to happen]
- The animation uses a default font found in the system

**Actual behavior:** [What actually happened]
- The app crashes with:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.android.lottie.rnexample, PID: 5238
    java.lang.RuntimeException: Font asset not found fonts/Roboto.ttf
        at android.graphics.Typeface.createFromAsset(Typeface.java:1044)
        at com.airbnb.lottie.manager.FontAssetManager.getFontFamily(FontAssetManager.java:90)
        at com.airbnb.lottie.manager.FontAssetManager.getTypeface(FontAssetManager.java:64)
        at com.airbnb.lottie.LottieDrawable.getTypeface(LottieDrawable.java:1250)
        at com.airbnb.lottie.model.layer.TextLayer.getTypeface(TextLayer.java:303)
        at com.airbnb.lottie.model.layer.TextLayer.drawTextWithFont(TextLayer.java:236)
        at com.airbnb.lottie.model.layer.TextLayer.drawLayer(TextLayer.java:163)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:128)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:250)
        at com.airbnb.lottie.LottieDrawable.drawDirectlyToCanvas(LottieDrawable.java:1354)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:517)
        at android.widget.ImageView.onDraw(ImageView.java:1446)
        at android.view.View.draw(View.java:23195)
        at android.view.View.updateDisplayListIfDirty(View.java:22062)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4579)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4290)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3517)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:832)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process: Sending signal. PID: 5238 SIG: 9
```

### Versions

You can get this information from executing `npm version`.

**Comment by alfonsocj** [comment]
I'll check today if this issue affects the paper implementation. If that's the case, this issue wouldn't be a blocker for the fabric release.

**Comment by AlexanderEggers** [comment]
@matinzd I had a try to fix this issue but had a no luck so far. Can you try to have another look when you got some time?

**Comment by matinzd** [comment]
@AlexanderEggers Of course. I will take a look at it next week.

**Comment by arctouch-andrecardoso** [comment]
I'm experiencing this crash using `v5.1.4` with expo 48. I tried adding the custom fonts used in the animation to the `ReactFontManager` as described in https://github.com/jsamr/react-native-font-demo#3-register-the-new-font but this library is not reading the fonts from there. 

Is there any other way to make animations work with custom fonts?

Thanks.

**Comment by arctouch-andrecardoso** [comment]
@lucatomarelli I ended up replacing the `LottiePackage` instance at `MainApplication`'s `ReactNativeHostWrapper#getPackages`  to return my own `LottieAnimationViewManager` class which is exactly the same as the one from this library but it sets my implementation of Lottie's `FontAssetDelegate` when the `LottieAnimationView` is created: 

```java
@Override public LottieAnimationView createViewInstance(ThemedReactContext context) {
        final LottieAnimationView view = new LottieAnimationView(context);
        view.setFontAssetDelegate(new ReactFontAssetDelegate(context));
        ...
```

and in my `ReactFontAssetDelegate` I delegate to `ReactFontManager` when getting the typeface:

```java
@Override
    public Typeface fetchFont(String fontFamily) {
        Log.d("ReactFontAssetDelegate", "fetching font " + fontFamily);
        return ReactFontManager.getInstance().getTypeface(fontFamily, 400, assets);
    }
```

**Comment by matinzd** [comment]
I think just adding this line to the lib itself would fix the issue if you load the font face with `ReactFontManager`:

```java
view.setFontAssetDelegate(new ReactFontAssetDelegate(context));
```
